/*******************************************************************************
 *  avast! Online Security plugin - Mustache.js HTML Templates - cross browser
 *  (c) 2014 Avast Corp.
 ******************************************************************************/

var AvastWRC = AvastWRC || {};


AvastWRC.Templates = {
  /**
   * Process templates declaration and append templates to container
   */
  add: function (declaration) {
    function addPart(acc, part) {
      if (part instanceof Array) {
        for (var i = 0; i < part.length; i++) {
          addPart(acc, part[i]);
        }
      } else if (part instanceof Object) {
        // reference within declaration
        if (part.temp) {
          var temp = declaration[part.temp] || AvastWRC.Templates[part.temp];
          addPart(acc, (part.sect !== undefined) ? temp[part.sect] : temp);
        }
      } else {
        acc.push(part);
      }
    }

    for (var temp in declaration) {
      var parts = [];
      addPart(parts, declaration[temp]);
      this[temp] = parts.join('\n');
    }
  }
};

/*------------------------ SafeShop bar UI templates -------------------------*/
AvastWRC.Templates.add(
  { // --- Templates Declaration
    safeShopPanel:[
      '<div translate="no" class="notranslate a-sp-panel" id="a-panel">',
        '<div class="a-sp-panel-header" id="a-panel-header">',
          '<img class="a-sp-header-top-left" src="{{images.logo}}"/>',
          '<div class="a-sp-header-top-right">',
          '<div class="sp-header-top-close" id="closePanel" style="background-image: url({{images.close}});">',
            '<div class="a-sp-tooltip a-sp-tooltip-hidden">{{strings.spCloseTooltip}}</div>',
          '</div>',
          '<div class="sp-header-top-min"  id="minPanel" style="background-image: url({{images.min}});">',
            '<div class="a-sp-tooltip a-sp-tooltip-hidden">{{strings.spMinimizeTooltip}}</div>',
          '</div>',
          '<div class="sp-header-top-help"  id="helpPanel" style="background-image: url({{images.help}});">',
            '<div class="a-sp-tooltip a-sp-tooltip-hidden">{{strings.spHelpTooltip}}</div>',
          '</div>',
          '<div class="sp-header-top-settings"  id="settingsPanel" style="background-image: url({{images.settings}});">',
            '<div class="a-sp-tooltip a-sp-tooltip-hidden">{{strings.spSettingsTooltip}}</div>',
          '</div>',
          '</div>',
          '<div class="a-sp-header-bottom-col1" id="offersTab">{{strings.spOffersTab}}<span id="offersTabState" class="{{^offersToBeShown}}a-sp-shown{{/offersToBeShown}}{{#offersToBeShown}}a-sp-to-be-shown{{/offersToBeShown}}"/>',          
          '</div>',
          '<div class="a-sp-header-bottom-separator-1-2">',
          '</div>',
          '<div class="a-sp-header-bottom-col2-selected" id="couponsTab">{{strings.spCouponsTab}}<span id="couponsTabState" class="{{^couponsToBeShown}}a-sp-shown{{/couponsToBeShown}}{{#couponsToBeShown}}a-sp-to-be-shown{{/couponsToBeShown}}"/>',
          '</div>',
          '<div class="a-sp-header-bottom-separator-2-3">',
          '</div>',
          '<div class="a-sp-header-bottom-col3" id="othersTab">{{strings.spOthersTab}}<span id="othersTabState" class="{{^othersToBeShown}}a-sp-shown{{/othersToBeShown}}{{#othersToBeShown}}a-sp-to-be-shown{{/othersToBeShown}}"/>',
          '</div>',
        '</div>',
        '<div class="a-sp-items-wrapper">',
          '<div id="offersWrapper">',
            {temp: 'nothingFoundOffers'},
          '</div>',
          '<div id="couponsWrapper">',
            {temp: 'nothingFoundCoupons'},
          '</div>',
          '<div id="othersWrapper">',
            {temp: 'nothingFoundOthers'},
          '</div>',
        '</div>',
        {temp: 'activeCoupons'},
        {temp: 'resizeBar'},

        // '<div class="asp-items-scrollbar-wrapper">',
        //   '<div class="asp-items-scrollbar"></div>',
        // '</div>',    
      '</div>',
    ],

    safeShopCouponPanel:[
      '<div translate="no" class="notranslate a-sp-coupon-panel" id="a-coupon-panel">',
        '<div class="a-sp-conteiner-top">',
          '<div class="a-sp-panel-header" id="couponPanelHeader">',
            '<img class="a-sp-panel-header-icon" src="{{appiedCouponData.images.logo}}"/>',
            '<div class="a-sp-panel-header-close" id="closeCouponPanel" style="background-image: url({{appiedCouponData.images.close}});"></div>',
          '</div>',
          '<div class="a-sp-applied-info">',
            '<img class="a-sp-panel-applied-icon" src="{{appiedCouponData.images.checkMarkIcon}}"/>',
            '<div class="a-sp-panel-applied-text">{{appiedCouponData.strings.sasCouponAppliedOnPage}}</div>',
          '</div>',
        '</div>',
        '<div class="asp-coupon-separator">',
          '<div class="asp-coupon-separator-left-top"></div>',
          '<div class="asp-coupon-separator-left-bottom"></div>',
          '<img class="asp-coupon-separator-middle-top" src="{{appiedCouponData.images.dashedLine}}"/>',
          '<img class="asp-coupon-separator-middle-bottom"/>',
          '<div class="asp-coupon-separator-right-top"></div>',
          '<div class="asp-coupon-separator-right-bottom"></div>',
        '</div>',
        '{{#coupons}}{{#selected}}',
          '<div class="asp-coupon-top">',
            '{{#value}}',
              '<div class="asp-coupon-item-value">',
                '<div class="asp-coupon-item-value-save">{{appiedCouponData.strings.save}}</div>',
                '<div class="asp-coupon-item-value-text">{{value}}</div>',
              '</div>',
              '<div class="asp-coupon-item-label">{{label}}</div>',
              '{{#coupon_text}}',
                '<div class="asp-coupon-description">',
                  '<div class="asp-coupon-description-text">{{coupon_text}}</div>',
                '</div>',
                '<div class="asp-coupon-description-more-info" id="more-info">{{appiedCouponData.strings.spNotificationRedirectShowMoreMessage}}</div>',
              '{{/coupon_text}}',              
              //'{{#expire_date_to_show}}<div class="asp-coupon-expiration">{{panelData.strings.spCouponsExpiration}} {{expire_date_to_show}}</div>{{/expire_date_to_show}}',
            '{{/value}}',
            '{{^value}}',
              '<div class="asp-coupon-item-label-full-size">{{label}}</div>',
              '{{#coupon_text}}', 
                '<div class="asp-coupon-description-full-size">',
                  '<div class="asp-coupon-description-full-size-text">{{coupon_text}}</div>',
                '</div>',
                '<div class="asp-coupon-description-more-info" id="more-info">{{appiedCouponData.strings.spNotificationRedirectShowMoreMessage}}</div>',
              '{{/coupon_text}}',
              //'{{#expire_date_to_show}}<div class="asp-coupon-expiration-full-size">{{panelData.strings.spCouponsExpiration}} {{expire_date_to_show}}</div>{{/expire_date_to_show}}',
            '{{/value}}',
          '</div>',
        '{{/selected}}{{/coupons}}',
      '</div>',
    ],

    // safeShopMinimizedPanel: [
    //     '<div id="asp-panel-min" class="asp-panel-minimized a-sp-notifications-hidden">',
    //       '<div class="asp-panel-minimized-inner">',
    //         '<img class="asp-panel-minimized-logo" src="{{templateData.images.loadingNotificationLogo}}"/>',
    //       '</div>',
    //       // '<div class="asp-minimized-panel-loader a-sp-notifications-hidden">',
    //       // '<svg class="circular" viewBox="25 25 50 50">',
    //       // '<circle class="path" cx="50" cy="50" r="24" fill="none" stroke-width="2" stroke-miterlimit="10"/>',
    //       // '</svg>',
    //       //'</div>',
    //       '<div id="asp-panel-min-badge" class="asp-panel-badge">',
    //         '<div class="asp-panel-badge-text"></div>',
    //       '</div>',
    //     '</div>',
    // ],


      safeShopMinimizedPanel: [
          '<div id="asp-panel-min" class="asp-panel-minimized-wrapper a-sp-notifications-hidden">',
              '<div id="asp-panel-minimized-top-circle" class="asp-panel-minimized-inner">',
                '<img class="asp-panel-minimized-logo" src="{{templateData.images.loadingNotificationLogo}}"/>',
              '</div>',
              '<div id="asp-panel-min-circle" class="asp-panel-minimized">',
                  '<div id="asp-panel-min-badge" class="asp-panel-badge">',
                    '<div class="asp-panel-badge-text"></div>',
                  '</div>',
              '</div>',
              '<div id="asp-panel-minimized-inner-circle" class="asp-panel-minimized-inner-circle"></div>',
          '</div>'
      ],


    //
    nothingFoundOffers:[
      '<div class="asp-nothing-found">',
        '<img class="nothing-found-icon" src="{{images.nothingFound}}"></img>',
        '<div class="nothing-found-text">{{{strings.spNothingFoundOffers}}}</div>',
      '</div>',
    ],
    nothingFoundCoupons:[
      '<div class="asp-nothing-found">',
        '<img class="nothing-found-icon" src="{{images.nothingFound}}"></img>',
        '<div class="nothing-found-text">{{{strings.spNothingFoundCoupons}}}</div>',
      '</div>',
    ],
    nothingFoundOthers:[
      '<div class="asp-nothing-found">',
        '<img class="nothing-found-icon" src="{{images.nothingFound}}"></img>',
        '<div class="nothing-found-text">{{{strings.spNothingFoundOthers}}}</div>',
      '</div>',
    ],
    // SafeShop Products dropdown
    offersWrapper:[
        '<div id="offersWrapper">',
        '{{#hotelsPriceComp}}',
          {temp: 'hotelItem'},
        '{{/hotelsPriceComp}}',
        '{{#hotelsCity.length}}',
          '<div class="asp-separator-text-first">{{panelData.strings.spCityHotelNotificationMessage}} <b>{{cityName}}</b></div>',
          '{{#hotelsCity}}',
          {temp: 'hotelItem'},
          '{{/hotelsCity}}',
        '{{/hotelsCity.length}}',
        '{{#hotelsSimilar.length}}',
        '<div class="asp-separator-text-first">{{panelData.strings.spSimilarHotelsMessage}}</div>',
          '{{#hotelsSimilar}}',
          {temp: 'hotelItem'},
          '{{/hotelsSimilar}}',
        '{{/hotelsSimilar.length}}',
        '{{#products}}',
          {temp: 'offerItem'},
        '{{/products}}',
        '{{#social.showInBottomOffers}}',
            {temp: 'socialSharing'},
        '{{/social.showInBottomOffers}}',
        '</div>',
    ],

    hotelItem:[
      '<div class="asp-offer-item" resurl="{{url}}">',
        '<div class="asp-offer-left">',
          '<img class="asp-offer-item-hotel-image" src="{{affiliate_image}}"/>',
        '</div>',
        '<div class="asp-offer-right">',
          '<div class="asp-offer-first-row">',
            '<div class="asp-offer-item-title">{{label}}</div>',
          '</div>',
          '<div class="asp-offer-second-row">',
            '{{#stars_to_show}}',
              {temp: 'starsRating'},
            '{{/stars_to_show}}',
          '</div>',
          '{{#additional_fees}}',
            '<div class="asp-offer-third-row">',
              '<div class="asp-offer-item-hotel-fee">{{panelData.strings.spAdditionalFees}}</div>',
            '</div>',
          '{{/additional_fees}}',
          '<div class="asp-offer-fourth-row">',
            '{{#is_long_price}}{{#fsaving}}{{#offerQuery.formatted_price}}',
            '<div class="asp-offer-item-price-stroke above">{{offerQuery.formatted_price}}</div>',
            '{{/offerQuery.formatted_price}}{{/fsaving}}{{/is_long_price}}',
          '</div>',
          {temp: 'offerBottomRow'},
        '</div>',
      '</div>'
    ],

    // SafeShop Products list item
    offerItem:[
      '<div class="asp-offer-item" resurl="{{url}}">',
        '<div class="asp-offer-left">',
            '<img class="asp-offer-item-image" src="{{affiliate_image}}"/>',
        '</div>',
        '<div class="asp-offer-right">',
          '<div class="asp-offer-first-row">',
            '<div class="asp-offer-item-title">{{label}}</div>',
          '</div>',
          '<div class="asp-offer-second-row">',
            '{{#shipping}}',
              '<div class="asp-offer-item-shipping">{{panelData.strings.spShippingLabel}} {{shipping}}</div>',
            '{{/shipping}}',
          '</div>',
          '<div class="asp-offer-third-row">',
            '{{#additional_fees}}',
            '<div class="asp-offer-item-hotel-fee">{{panelData.strings.spAdditionalFees}}</div>',
            '{{/additional_fees}}',
          '</div>',
          '<div class="asp-offer-fourth-row">',
            '{{#is_long_price}}{{#fsaving}}{{#offerQuery.formatted_price}}',
              '<div class="asp-offer-item-price-stroke above">{{offerQuery.formatted_price}}</div>',
            '{{/offerQuery.formatted_price}}{{/fsaving}}{{/is_long_price}}',
          '</div>',
          {temp: 'offerBottomRow'},
        '</div>',
      '</div>'
    ],

    offerBottomRow: [
        '{{#is_long_price}}',
          '<div class="asp-offer-fifth-row">',
        '{{/is_long_price}}',
        '{{^is_long_price}}',
          '{{#fsaving}}',
            '<div class="asp-offer-fifth-row top-space">',
          '{{/fsaving}}',
          '{{^fsaving}}',
            '<div class="asp-offer-fifth-row">',
          '{{/fsaving}}',
        '{{/is_long_price}}',
          '{{#fsaving}}',
            '<div class="asp-offer-item-discount-banner"><span class="asp-offer-item-discount-text">{{fsaving}}</span></div>',
          '{{/fsaving}}',
          '{{^fsaving}}',
            '<div class="asp-blank-div"></div>',
          '{{/fsaving}}',
          '{{#is_long_price}}',
            '<div class="asp-blank-div"></div>',
          '{{/is_long_price}}',
          '{{^is_long_price}}',
            '{{#offerQuery.formatted_price}}{{#fsaving}}',
              '<div class="asp-offer-item-price-stroke">{{offerQuery.formatted_price}}</div>',
            '{{/fsaving}}{{/offerQuery.formatted_price}}',
            '{{^offerQuery.formatted_price}}',
              '<div class="asp-blank-div"></div>',
            '{{/offerQuery.formatted_price}}',
          '{{/is_long_price}}',
          '{{#show_price}}',
            '<div class="asp-offer-item-price">{{fprice}}</div>',
          '{{/show_price}}',
          '{{^show_price}}',
            '<div class="asp-blank-div"></div>',
          '{{/show_price}}',
        '</div>'
    ],

    couponsWrapper:[
      '<div id="couponsWrapper">',
        '{{#vouchersSelected}}',
          {temp: 'separatorTextFirst'},
          {temp: 'selectedCoupons'},
          {temp: 'separatorTextSecond'},
          {temp: 'notSelectedCoupons'},
        '{{/vouchersSelected}}',
        '{{^vouchersSelected}}',          
          {temp: 'notSelectedCoupons'},
        '{{/vouchersSelected}}',
        '{{#social.showInBottomCoupons}}',
          {temp: 'socialSharing'},
        '{{/social.showInBottomCoupons}}',
      '</div>',
    ],

    separatorTextFirst: [
      '<div id="asp-separator-text-first" class="asp-separator-text-first {{#selectedCouponAnimation}}asp-separator-text-hidden{{/selectedCouponAnimation}}">{{panelData.strings.spCouponsSelectedText}}</div>',
    ],

    separatorTextSecond: [
      '{{#vouchersAvailable}}<div class="asp-separator-text {{#selectedCouponAnimation}}asp-separator-text-hidden{{/selectedCouponAnimation}}">{{panelData.strings.spCouponsAvailableText}}</div>{{/vouchersAvailable}}',
    ],

    notSelectedCoupons:[
      '{{#coupons}}{{^selected}}',
              '<div class="asp-coupon-item" id="coupon" resurl="{{url}}">',
                '<div class="asp-coupon-top">',
                  '{{#value}}',
                    '<div class="asp-coupon-item-value">',
                      '<div class="asp-coupon-item-value-save">{{panelData.strings.save}}</div>',
                      '<div class="asp-coupon-item-value-text">{{value}}</div>',
                    '</div>',
                    '<div class="asp-coupon-item-label">{{label}}</div>',
                    '{{#coupon_text}}',
                      '<div class="asp-coupon-description">',
                        '<div class="asp-coupon-description-text">{{coupon_text}}</div>',
                      '</div>',
                      '<div class="asp-coupon-description-more-info" id="more-info">{{panelData.strings.spNotificationRedirectShowMoreMessage}}</div>',
                    '{{/coupon_text}}',
                    //'{{#expire_date_to_show}}<div class="asp-coupon-expiration">{{panelData.strings.spCouponsExpiration}} {{expire_date_to_show}}</div>{{/expire_date_to_show}}',
                  '{{/value}}',
                  '{{^value}}',
                    '<div class="asp-coupon-item-label-full-size">{{label}}</div>',
                    '{{#coupon_text}}',
                      '<div class="asp-coupon-description-full-size">',
                        '<div class="asp-coupon-description-full-size-text">{{coupon_text}}</div>',
                      '</div>',
                      '<div class="asp-coupon-description-more-info" id="more-info">{{panelData.strings.spNotificationRedirectShowMoreMessage}}</div>',
                    '{{/coupon_text}}',
                    //'{{#expire_date_to_show}}<div class="asp-coupon-expiration-full-size">{{panelData.strings.spCouponsExpiration}} {{expire_date_to_show}}</div>{{/expire_date_to_show}}',
                  '{{/value}}',
                '</div>',
                '<div class="asp-coupon-separator">',
                  '<div class="asp-coupon-separator-left"></div>',
                  '<img class="asp-coupon-separator-middle" src="{{panelData.images.dashedLine}}"/>',
                  '<div class="asp-coupon-separator-right"></div>',
                '</div>',
                '<div class="asp-coupon-bottom"  id="coupon" resurl="{{url}}">',
                  '<div class="asp-coupon-item-get-coupon">',
                    '{{#coupon_code}}{{panelData.strings.spGetCouponCode}}{{/coupon_code}}',
                    '{{^coupon_code}}{{panelData.strings.spApply}}{{/coupon_code}}',
                  '</div>',
                '</div>',
              '</div>',
      '{{/selected}}{{/coupons}}',
    ],

    selectedCoupons: [
        '{{#coupons}}',
          '{{#selected}}',
            {temp: 'selectedCoupon'},
          '{{/selected}}',
        '{{/coupons}}'
    ],

    selectedCoupon:[
        '<div class="asp-coupon-item-active{{#coupon_code}}-with-code{{/coupon_code}}" id="coupon" resurl="{{url}}">',
          '<div class="asp-coupon-top">',
            '{{#value}}',
              '<div class="asp-coupon-item-value">',
                '<div class="asp-coupon-item-value-save">{{panelData.strings.save}}</div>',
                '<div class="asp-coupon-item-value-text">{{value}}</div>',
              '</div>',
              '<div class="asp-coupon-item-label">{{label}}</div>',
                '{{#coupon_text}}',
                  '<div class="asp-coupon-description">',
                    '<div class="asp-coupon-description-text">{{coupon_text}}</div>',
                  '</div>',
                  '<div class="asp-coupon-description-more-info" id="more-info">{{panelData.strings.spNotificationRedirectShowMoreMessage}}</div>',
                '{{/coupon_text}}',
            //'{{#expire_date_to_show}}<div class="asp-coupon-expiration">{{panelData.strings.spCouponsExpiration}} {{expire_date_to_show}}</div>{{/expire_date_to_show}}',
            '{{/value}}',
          '{{^value}}',
            '<div class="asp-coupon-item-label-full-size">{{label}}</div>',
            '{{#coupon_text}}',
              '<div class="asp-coupon-description-full-size">',
                '<div class="asp-coupon-description-full-size-text">{{coupon_text}}</div>',
              '</div>',
              '<div class="asp-coupon-description-more-info" id="more-info">{{panelData.strings.spNotificationRedirectShowMoreMessage}}</div>',
            '{{/coupon_text}}',
            //'{{#expire_date_to_show}}<div class="asp-coupon-expiration-full-size">{{panelData.strings.spCouponsExpiration}} {{expire_date_to_show}}</div>{{/expire_date_to_show}}',
          '{{/value}}',
        '</div>',
        '<div class="asp-coupon-separator">',
          '<div class="asp-coupon-separator-left"></div>',
          '<img class="asp-coupon-separator-middle" src="{{panelData.images.dashedLine}}"/>',
          '<div class="asp-coupon-separator-right"></div>',
        '</div>',
        '{{#coupon_code}}',
            '<div class="asp-coupon-bottom-with-code" cupcod="{{coupon_code}}">',
              '<div class="asp-coupon-item-copy-code {{#selectedCouponAnimation}}asp-coupon-item-code-animation{{/selectedCouponAnimation}}">{{panelData.strings.spCopyAtCheckOut}}</div>',
              '<div class="asp-coupon-item-coupon-code {{#selectedCouponAnimation}}asp-coupon-item-code-animation{{/selectedCouponAnimation}}">{{coupon_code}}</div>',
          '</div>',
        '{{/coupon_code}}',
        '{{^coupon_code}}',
          '<div class="asp-coupon-bottom-without-code">',
            '<div class="asp-coupon-item-coupon-applied">{{panelData.strings.spCouponApplied}}<span class="asp-open-shop" resurl="{{url}}">{{panelData.strings.sasOpenShop}}</span>',
            '</div>',
          '</div>',
        '{{/coupon_code}}',
      '</div>',
    ],

    activeCoupons:[
      '{{#vouchersSelected}}{{#vouchersSelectedCounter}}',
        '<div class="a-sp-active-coupons-message" id="activeCoupons">',
          '<div class="a-sp-active-coupons-info">{{panelData.strings.spCouponsSelected}}',
              '<span class="asp-active-coupons-badge{{#vouchersCounterBig}}-big{{/vouchersCounterBig}}">{{vouchersSelectedCounter}}</span>',            
          '</div>',         
        '</div>',
        '{{/vouchersSelectedCounter}}{{/vouchersSelected}}',
    ],

    resizeBar:[
      '<div class="a-sp-items-wrapper-resize" id="panel-resize">',
        '<div class="a-sp-resize-handle-1"></div>',
        '<div class="a-sp-resize-handle-2"></div>',
      '</div>',
    ],

    othersWrapper:[
      '<div id="othersWrapper">',
        '{{#isRedirect}}',
          '<div class="asp-redirect-item" id="redirect" resurl="{{url}}">',
            {temp: "notificationRedirectContent"},  
          '</div>',
        '{{/isRedirect}}',
        '{{#isSimilarCoupons}}',
          '<div class="asp-similar-coupon-item" id="similarCoupon" resurl="{{similarCoupon.url}}">',
            {temp: "similarCouponsNotification"},  
            {temp: "notificationsButton"},  
          '</div>',
        '{{/isSimilarCoupons}}',
      '</div>',
    ],

    starsRating: [
        '<div class="asp-rating-stars-wrapper">',
        '{{#stars}}',
        '<i class="asp-rating-star" style="background-image: url({{.}});"></i>',
        '{{/stars}}',
        '</div>'
    ],

    copiedToClipboard: [
      '<div class="asp-copied-to-clipboard">{{panelData.strings.sasCouponCodeCopied}}</div>'
    ],

    safeShopSettingsPopup : [
      '<div class="asp-settings-page">',
        '<div class="asp-settings-poppup">',
          '{{^isChrome}}{{^isAvast}}',
            '<div class="asp-settings-title-box">',
              '{{#isFirefox}}',
                '<div class="asp-settings-title-text">{{poppupSettings.strings.sasHintSettings}}</div>',
              '{{/isFirefox}}',
              '{{^isFirefox}}',
                '<img class="asp-settings-title-icon" src={{poppupSettings.images.logo}}></img>',
                '<div class="asp-settings-title-text">',
                  '{{#avastBranding}}',
                    '{{poppupSettings.strings.spSettingsPageTitleAvast}}',
                  '{{/avastBranding}}',
                  '{{^avastBranding}}',
                    '{{poppupSettings.strings.spSettingsPageTitleAvg}}',
                  '{{/avastBranding}}',
                '</div>',
                '<div class="asp-settings-title-close" id="asp-popup-settings-close" style="background-image: url({{poppupSettings.images.close}});"></div>',
              '{{/isFirefox}}',
            '</div>',
          '{{/isAvast}}{{/isChrome}}',
          '<div class="asp-middle-box">',
            '<div class="asp-middle-menu">',
              '<div class="asp-middle-item-notifications{{#poppupSettings.menuOpt.notifications.selected}}-selected{{/poppupSettings.menuOpt.notifications.selected}}" id="sp-menu-notifications">',
                '{{poppupSettings.strings.spSettingsTabNotifications}}',
              '</div>', 
              '<div class="asp-middle-item-custom-list{{#poppupSettings.menuOpt.customList.selected}}-selected{{/poppupSettings.menuOpt.customList.selected}}" id="sp-menu-customList">',
                '{{poppupSettings.strings.spSettingsPageCustomList}}',
              '</div>', 
              '<div class="asp-middle-item-help{{#poppupSettings.menuOpt.help.selected}}-selected{{/poppupSettings.menuOpt.help.selected}}" id="sp-menu-help">',
                '{{poppupSettings.strings.spSettingsPageHelp}}',
              '</div>', 
            '</div>',
            '<div class="asp-middle-options">',
              '<div class="asp-middle-panel-notifications {{#poppupSettings.menuOpt.notifications.selected}}asp-display-grid{{/poppupSettings.menuOpt.notifications.selected}}" id="sp-panel-notifications-options">',
                '<div class="asp-tabs">',
                  '<div class="asp-offers-tab-selected" id="tabOffer">',
                    '{{poppupSettings.strings.spSettingsTabNotificationsOffers}}',
                  '</div>',
                  '<div class="asp-coupons-tab" id="tabCoupon">',
                    '{{poppupSettings.strings.spSettingsTabNotificationsCoupons}}',
                  '</div>',
                  '<div class="asp-others-tab"  id="tabOther">',
                  '{{poppupSettings.strings.spSettingsTabNotificationsOthers}}',
                  '</div>',
                '</div>',
                '<div class="asp-tabs-content-selected" id="contentOffers">',
                  '<div class="asp-title-offers">',
                    '{{poppupSettings.strings.spSettingsTabNotificationsOffersTitle}}',
                  '</div>',
                  '<div class="asp-offers-show-all{{#poppupSettings.menuOpt.notifications.offers.showAlways}}-selected{{/poppupSettings.menuOpt.notifications.offers.showAlways}}" id="offersShowAll">',
                    '<div class="asp-radio-button">',
                    '</div>',
                    '<div class="asp-desc">',
                      '{{poppupSettings.strings.spSettingsTabNotificationsOffersShowAll}}',
                    '</div>',
                  '</div>',
                  '<div class="asp-offers-show-better{{#poppupSettings.menuOpt.notifications.offers.showBetter}}-selected{{/poppupSettings.menuOpt.notifications.offers.showBetter}}" id="offersShowBetter">',
                    '<div class="asp-radio-button">',
                    '</div>',
                    '<div class="asp-desc">',
                      '{{poppupSettings.strings.spSettingsTabNotificationsOffersBetter}}',
                    '</div>',
                  '</div>',
                  '<div class="asp-offers-hide{{#poppupSettings.menuOpt.notifications.offers.hide}}-selected{{/poppupSettings.menuOpt.notifications.offers.hide}}" id="offersHide">',
                      '<div class="asp-radio-button">',
                      '</div>',
                      '<div class="asp-desc">',
                        '{{poppupSettings.strings.spSettingsTabNotificationsOffersHideAll}}',
                      '</div>',
                      '<div class="asp-radio-button-option-desc">',
                        '{{poppupSettings.strings.spSettingsTabNotificationsOffersHideAllDesc}}',
                      '</div>',
                  '</div>',
                  '<div class="asp-title-accommodations">',
                    '{{poppupSettings.strings.spSettingsTabNotificationAccommodationsTitle}}',
                  '</div>',
                  '<div class="asp-accommodations-show-better" id="accommodationsShowBetter">',
                    '{{#poppupSettings.menuOpt.notifications.accommodations.showBetter}}<img class="asp-check-box"src="{{poppupSettings.images.checkboxChecked}}" id="checkboxAccommodationsShowBetter">{{/poppupSettings.menuOpt.notifications.accommodations.showBetter}}',
                    '{{^poppupSettings.menuOpt.notifications.accommodations.showBetter}}<img class="asp-check-box"src="{{poppupSettings.images.checkbox}}" id="checkboxAccommodationsShowBetter">{{/poppupSettings.menuOpt.notifications.accommodations.showBetter}}',
                    '<div class="asp-desc">',
                      '{{poppupSettings.strings.spSettingsTabNotificationsAccommodationsShowBetter}}',
                    '</div>',
                  '</div>',
                  '<div class="asp-accommodations-show-similar" id="accommodationsShowSimilar">',
                    '{{#poppupSettings.menuOpt.notifications.accommodations.showSimilar}}<img class="asp-check-box"src="{{poppupSettings.images.checkboxChecked}}" id="checkboxAccommodationsShowSimilar">{{/poppupSettings.menuOpt.notifications.accommodations.showSimilar}}',
                    '{{^poppupSettings.menuOpt.notifications.accommodations.showSimilar}}<img class="asp-check-box"src="{{poppupSettings.images.checkbox}}" id="checkboxAccommodationsShowSimilar">{{/poppupSettings.menuOpt.notifications.accommodations.showSimilar}}',
                    '<div class="asp-desc">',
                      '{{poppupSettings.strings.spSettingsTabNotificationsAccommodationsSimilar}}',
                    '</div>',
                  '</div>',
                  '<div class="asp-accommodations-show-popular" id="accommodationsShowPopular">',
                    '{{#poppupSettings.menuOpt.notifications.accommodations.showPopular}}<img class="asp-check-box"src="{{poppupSettings.images.checkboxChecked}}" id="checkboxAccommodationsShowPopular">{{/poppupSettings.menuOpt.notifications.accommodations.showPopular}}',
                    '{{^poppupSettings.menuOpt.notifications.accommodations.showPopular}}<img class="asp-check-box"src="{{poppupSettings.images.checkbox}}" id="checkboxAccommodationsShowPopular">{{/poppupSettings.menuOpt.notifications.accommodations.showPopular}}',
                    '<div class="asp-desc">',
                      '{{poppupSettings.strings.spSettingsTabNotificationsAccommodationsPopular}}',
                    '</div>',
                  '</div>',
                '</div>',
                '<div class="asp-tabs-content" id="contentCoupons">',
                  '<div class="asp-title-coupons">',
                    '{{poppupSettings.strings.spSettingsTabNotificationsCoupons}}',
                  '</div>',
                  '<div class="asp-coupons-show-all{{#poppupSettings.menuOpt.notifications.coupons.showAlways}}-selected{{/poppupSettings.menuOpt.notifications.coupons.showAlways}}" id="couponsShowAll">',
                    '<div class="asp-radio-button">',
                    '</div>',
                    '<div class="asp-desc">',
                      '{{poppupSettings.strings.spSettingsTabNotificationsCouponsShowAll}}',
                    '</div>',
                  '</div>',
                  '<div class="asp-coupons-show-once{{#poppupSettings.menuOpt.notifications.coupons.showOnce}}-selected{{/poppupSettings.menuOpt.notifications.coupons.showOnce}}" id="couponsShowOnce">',
                    '<div class="asp-radio-button">',
                    '</div>',
                    '<div class="asp-desc">',
                      '{{poppupSettings.strings.spSettingsTabNotificationsCouponsShowOnce}}',
                    '</div>',
                  '</div>',
                  '<div class="asp-coupons-hide{{#poppupSettings.menuOpt.notifications.coupons.hide}}-selected{{/poppupSettings.menuOpt.notifications.coupons.hide}}" id="couponsHide">',
                      '<div class="asp-radio-button">',
                      '</div>',
                      '<div class="asp-desc">',
                        '{{poppupSettings.strings.spSettingsTabNotificationsCouponsHide}}',
                      '</div>',
                      '<div class="asp-radio-button-option-desc">',
                        '{{poppupSettings.strings.spSettingsTabNotificationsCouponsHideDesc}}',
                      '</div>',
                  '</div>',
                '</div>',
                '<div class="asp-tabs-content" id="contentOthers">',
                  '<div class="asp-title-others">',
                    '{{poppupSettings.strings.spSettingsTabNotificationsOthers}}',
                  '</div>',
                  '<div class="asp-others-show-all" id="othersShowAll">',
                    '{{#poppupSettings.menuOpt.notifications.others.showAlways}}<img class="asp-check-box"src="{{poppupSettings.images.checkboxChecked}}" id="checkboxOthersShowAll">{{/poppupSettings.menuOpt.notifications.others.showAlways}}',
                    '{{^poppupSettings.menuOpt.notifications.others.showAlways}}<img class="asp-check-box"src="{{poppupSettings.images.checkbox}}" id="checkboxOthersShowAll">{{/poppupSettings.menuOpt.notifications.others.showAlways}}',
                    '<div class="asp-desc">',
                      '{{poppupSettings.strings.spSettingsTabNotificationsOthersDesc}}',
                    '</div>',
                  '</div>',
                '</div>',
              '</div>',                
              '<div class="asp-middle-panel-custom-list {{#poppupSettings.menuOpt.customList.selected}}asp-display-grid{{/poppupSettings.menuOpt.customList.selected}}"  id="sp-panel-customList-options">',
                '<div class="asp-p-cl-title">',
                  '{{poppupSettings.strings.spSettingsPageCustomListTitle}}',
                '</div>',
                '<div class="asp-p-cl-title-desc">',
                  '{{poppupSettings.strings.spSettingsPageCustomListTitleDesc}}',
                '</div>',
                '<div class="asp-p-cl-add-site-button {{#poppupSettings.menuOpt.customList.showAddButton}}asp-display-block{{/poppupSettings.menuOpt.customList.showAddButton}}" id="add-site-button-to-box">',
                  '<div class="asp-p-cl-add-site-button-icon" style="background-image: url({{poppupSettings.images.add}});"></div>', 
                  '<div class="asp-p-cl-add-site-button-text">',
                    '{{poppupSettings.strings.spSettingsPageCustomListItemAddSite}}',
                  '</div>', 
                '</div>',
                '<div class="asp-p-cl-add-site-box {{^poppupSettings.menuOpt.customList.showAddButton}}asp-display-block{{/poppupSettings.menuOpt.customList.showAddButton}}" id="add-site-box">',
                  '<input type="text" class="asp-p-cl-add-site-text" id="new-site-name" autofocus>',
                  '<div class="asp-p-cl-add-site-add" id="add-site-add">',
                    '{{poppupSettings.strings.spSettingsPageCustomListItemAdd}}',
                  '</div>', 
                  '<div class="asp-p-cl-add-site-cancel" id="add-site-cancel">',
                    '{{poppupSettings.strings.spSettingsPageCancel}}',
                  '</div>', 
                '</div>', 
                '<div class="asp-p-cl-sites-box">',
                  '{{#poppupSettings.menuOpt.customList.whiteList.length}}',
                    '{{#poppupSettings.menuOpt.customList.whiteList}}',
                      '<div class="asp-p-cl-box-element">',
                        '<div class="asp-p-cl-box-element-text">',
                          '{{.}}',
                        '</div>',
                        '<div class="asp-p-cl-box-element-close" style="background-image: url({{poppupSettings.images.erase}});">',
                        '</div>',
                      '</div>',
                    '{{/poppupSettings.menuOpt.customList.whiteList}}',
                  '{{/poppupSettings.menuOpt.customList.whiteList.length}}',
                '</div>',
              '</div>',
              '<div class="asp-middle-panel-help {{#poppupSettings.menuOpt.help.selected}}asp-display-grid{{/poppupSettings.menuOpt.help.selected}}"  id="sp-panel-help-options">', 
                '<div class= "asp-help-group-1">',
                  '<div class= "asp-help-title">{{poppupSettings.strings.spSettingsPageHelpNotificationsTitle}}</div>',
                  '<div class= "asp-help-title-desc">{{poppupSettings.strings.spSettingsPageHelpNotificationsTitleDesc}}</div>',
                '</div>',
                '<div class= "asp-help-group-2">',
                  '<div class= "asp-help-title">{{poppupSettings.strings.spSettingsPageHelpOffersTitle}}</div>',
                  '<div class= "asp-help-title-desc">{{poppupSettings.strings.spSettingsPageHelpOffersTitleDesc}}</div>',
                '</div>',
                '<div class= "asp-help-group-3">',
                  '<div class= "asp-help-title">{{poppupSettings.strings.spSettingsPageHelpCouponsTitle}}</div>',
                  '<div class= "asp-help-title-desc">{{poppupSettings.strings.spSettingsPageHelpCouponsTitleDesc}}</div>',
                '</div>',
                '<div class= "asp-help-group-4">',
                  '<div class= "asp-help-title">{{poppupSettings.strings.spSettingsPageHelpOthersTitle}}</div>',
                  '<div class= "asp-help-title-desc">{{poppupSettings.strings.spSettingsPageHelpOthersTitleDesc}}</div>',
                '</div>',
                '<div class= "asp-help-faqs">{{{poppupSettings.strings.spSettingsPageHelpFAQsTitle}}}</div>',
              '</div>',
            '</div>',
          '</div>',
          '<div class="asp-settings-footer-box">',
            '{{^isFirefox}}',
              '<div class="asp-settings-footer-cancel" id="asp-popup-settings-cancel">',
                '{{poppupSettings.strings.spSettingsPageCancel}}',
              '</div>',
            '{{/isFirefox}}',
            '<div class="asp-settings-footer-save" id="asp-poppup-settings-save">',
              '{{poppupSettings.strings.spSettingsPageSave}}',
            '</div>',
          '</div>',
        '</div>',
      '</div>',
    ],

    whiteListElement : [
      '<div class="asp-p-cl-box-element">',
        '<div class="asp-p-cl-box-element-text">',
          '{{site}}',
        '</div>',
        '<div class="asp-p-cl-box-element-close" style="background-image: url({{icon}});">',
        '</div>',
      '</div>',
    ],

    notification: [
        '<div class="a-sp-notifications a-sp-notifications-hidden notranslate" id="a-sp-notifications-standard">',
          '<div class="a-sp-notifications-header" id="a-sp-notifications-header-drag">',
            '<img class="a-sp-notifications-header-logo-icon" src="{{templateData.images.loadingNotificationLogo}}"/>',
            '<img class="a-sp-notifications-header-gear-icon" src="{{templateData.images.loadingNotificationGear}}"/>',
            '<img class="a-sp-notifications-header-close-icon" src="{{templateData.images.loadingNotificationClose}}"/>',
          '</div>',
          '<div class="a-sp-loading-notification a-sp-notifications-hidden">',
            '<img class="a-sp-loading-notification-img" src="{{templateData.images.loadingGIF}}"/>',
            '<p class="a-sp-loading-notification-text">{{{templateData.strings.spLoadingNotificationMessage}}}</p>',
            '<p class="a-sp-loading-notification-description">{{templateData.strings.spLoadingNotificationDescriptionMessage}}</p>',
          '</div>',
          '<div class="a-sp-coupons-notification a-sp-notifications-hidden">',
            '<img class="a-sp-coupons-notification-img" src="{{templateData.images.couponsPanel}}"/>',
            '<img class="a-sp-coupons-notification-img-animated a-sp-notification-img-hidden" src="{{templateData.animations.couponsPanel}}"/>',
            '<p class="a-sp-coupons-notification-text">{{templateData.strings.spCouponsNotificationMessage}}</p>',
          '</div>',
          '<div class="a-sp-offers-notification a-sp-notifications-hidden">',
            '<img class="a-sp-offers-notification-img" src="{{templateData.images.moreOffersPanel}}"/>',
            '<img class="a-sp-offers-notification-img-animated a-sp-notification-img-hidden" src="{{templateData.animations.betterOffersPanel}}"/>',
            '<p class="a-sp-offers-notification-text">{{{templateData.strings.spBetterOffersNotificationMessage}}}</p>',
          '</div>',
          '<div class="a-sp-offers-coupons-notification a-sp-notifications-hidden">',
            '<img class="a-sp-offers-coupons-notification-img" src="{{templateData.images.offersAndCouponsPanel}}"/>',
            '<img class="a-sp-offers-coupons-notification-img-animated a-sp-notification-img-hidden" src="{{templateData.animations.offersAndCouponsPanel}}"/>',
            '<p class="a-sp-offers-coupons-notification-text">{{{templateData.strings.spOffersAndCouponsNotificationMessage}}}</p>',
          '</div>',
          {temp:"similarCouponsNotification"},
          '<div class="a-sp-city-hotels-notification a-sp-notifications-hidden">',
            '<img class="a-sp-city-hotels-notification-img" src="{{templateData.images.hotelsPanel}}">',
            '<img class="a-sp-city-hotels-notification-img-animated a-sp-notification-img-hidden" src="{{templateData.animations.hotelsPanel}}">',
            '<p class="a-sp-city-hotels-notification-text">{{templateData.strings.spCityHotelNotificationMessage}}<br><span class="a-sp-city-hotels-notification-text-city"></span></p>',
          '</div>',
          '<div class="a-sp-similar-hotels-notification a-sp-notifications-hidden">',
            '<img class="a-sp-similar-hotels-notification-img" src="{{templateData.images.hotelsPanel}}"/>',
            '<img class="a-sp-similar-hotels-notification-img-animated a-sp-notification-img-hidden" src="{{templateData.animations.hotelsPanel}}"/>',
            '<p class="a-sp-similar-hotels-notification-text">{{{templateData.strings.spSimilarHotelsNotificationMessage}}}</p>',
          '</div>',
          {temp: "notificationsButton"},
        '</div>',
    ],

    similarCouponsNotification: [
      '<div class="a-sp-deals-notification {{^isPanelTemplate}}a-sp-notifications-hidden{{/isPanelTemplate}}">',
          '<img class="a-sp-deals-notification-img {{#isPanelTemplate}}a-sp-notification-img-hidden{{/isPanelTemplate}}" src="{{templateData.images.specialDealsPanel}}"/>',
          '<img class="a-sp-deals-notification-img-animated {{^isPanelTemplate}}a-sp-notification-img-hidden{{/isPanelTemplate}}" src="{{templateData.animations.specialDealsPanel}}"/>',
          '<p class="a-sp-deals-notification-text">{{{templateData.strings.spBetterSpecialDealsNotificationMessage}}}</p>',
      '</div>',
    ],

    notificationsButton: [
      '{{#isPanelTemplate}}<div class="a-sp-notifications-button {{#redirect.infoText}}space-down{{/redirect.infoText}}" id="similarCouponsButton" resurl="{{similarCoupon.url}}">{{/isPanelTemplate}}',
      '{{^isPanelTemplate}}<div class="a-sp-notifications-button {{#redirect.infoText}}space-down{{/redirect.infoText}}" id="similarCouponsButtonStandard" resurl="{{similarCoupon.url}}">{{/isPanelTemplate}}',
          '<span class="a-sp-notifications-button-show" >',
              '{{templateData.strings.spShowNotificationMessage}}',
          '</span>',
          '<span class="a-sp-notifications-button-show-amount">{{#isPanelTemplate}}{{similarCoupon.value}}{{/isPanelTemplate}}</span>',
      '</div>',
    ],

    notificationRedirect: [
      '<div class="a-sp-notifications-redirect notranslate" id="a-sp-notifications-redirect">',
        '<div class="a-sp-notifications-redirect-header" id="a-sp-notifications-redirect-header-drag">',
            '<img class="a-sp-notifications-redirect-header-logo-icon" src="{{templateData.images.loadingNotificationLogo}}">',
            '<img class="a-sp-notifications-redirect-header-gear-icon" src="{{templateData.images.loadingNotificationGear}}">',
            '<img class="a-sp-notifications-redirect-header-close-icon" src="{{templateData.images.loadingNotificationClose}}">',
        '</div>',        
        {temp: "notificationRedirectContent"},       
      '</div>',
    ],
    notificationRedirectContent: [
      {temp: "notificationRedirectImageContainer"},
      '<div class="a-sp-notifications-redirect-title">{{redirect.label}}</div>',
      '<div class="a-sp-notifications-redirect-price">{{redirect.availability}}</div>',
      '<div class="a-sp-notifications-redirect-button-show" {{#isPanelTemplate}}id="redirectButton"{{/isPanelTemplate}} resurl="{{redirect.url}}">{{redirect.buttonText}}</div>',
      '{{^redirect.infoText}}',
      '{{/redirect.infoText}}',
      '<div class="a-sp-notifications-redirect-after-button-row"></div>',
      '{{#redirect.infoText}}',
          '<div class="a-sp-notifications-redirect-info" {{#isPanelTemplate}}id="redirectMoreInfo"{{/isPanelTemplate}}>',
              '<span class="a-sp-notifications-redirect-info-more a-sp-notifications-redirect-info-toggle-text">{{templateData.strings.spNotificationRedirectShowMoreMessage}}</span>',
              '<span class="a-sp-notifications-redirect-info-less a-sp-notifications-redirect-info-toggle-text a-sp-notifications-hidden">{{templateData.strings.spNotificationRedirectShowLessMessage}}</span>',
              '<img src="{{templateData.images.shape}}" class="a-sp-notifications-redirect-info-icon">',
              '<div class="a-sp-notifications-redirect-info-toggle-text-padding a-sp-notifications-redirect-info-toggle-text"> </div>',
              '<div class="a-sp-notifications-redirect-info-text a-sp-notifications-hidden">{{redirect.infoText}}</div>',
          '</div>',
      '{{/redirect.infoText}}',
    ],
    notificationRedirectImageContainer: [
        '<div class="a-sp-notifications-redirect-image-title">{{templateData.strings.spShowNotificationRedirectMessage}}</div>',
        '{{#redirect.image}}{{^redirect.primaryImage}}{{^redirect.secondaryImage}}',
          '<img class="a-sp-notifications-redirect-default-img" src="{{redirect.image}}" {{#isPanelTemplate}}id="redirectImageDefault"{{/isPanelTemplate}}>',
        '{{/redirect.secondaryImage}}{{/redirect.primaryImage}}{{/redirect.image}}',
        '{{^redirect.image}}{{^redirect.primaryImage}}{{^redirect.secondaryImage}}',
          '<img class="a-sp-notifications-redirect-default-img" src="{{templateData.images.specialDealsGIF}}">',
        '{{/redirect.secondaryImage}}{{/redirect.primaryImage}}{{/redirect.image}}',
        '{{#redirect.primaryImage}}{{#redirect.secondaryImage}}',
          '<img class="a-sp-notifications-redirect-img {{#isPanelTemplate}}a-sp-notification-img-hidden{{/isPanelTemplate}}" src="{{redirect.primaryImage}}"/>',
          '<img class="a-sp-notifications-redirect-img-animated {{^isPanelTemplate}}a-sp-notification-img-hidden{{/isPanelTemplate}}" {{#isPanelTemplate}}id="redirectImage"{{/isPanelTemplate}} src="{{redirect.secondaryImage}}"/>',
        '{{/redirect.secondaryImage}}{{/redirect.primaryImage}}',
    ],
    notificationBar: [
        '<div class="asp-notifications-bar-wrapper a-sp-notifications-hidden notranslate" id="asp-notifications-bar">',
          '<img class="asp-notifications-bar-logo" src="{{templateData.images.loadingNotificationLogo}}"/>',
          '<div class="asp-notifications-bar-content">',
            '<div class="asp-notifications-bar-offers a-sp-notifications-hidden">',
              '<img class="asp-notifications-bar-image" src="{{templateData.images.moreOffersBar}}"/>',
              '<img class="asp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{templateData.animations.moreOffersBar}}"/>',
              '<div class="asp-notifications-bar-text">{{templateData.strings.spBetterOffersNotificationBarMessage}}</div>',
            '</div>',
            '<div class="asp-notifications-bar-alt-hotels a-sp-notifications-hidden">',
              '<img class="asp-notifications-bar-image" src="{{templateData.images.hotelsBar}}"/>',
              '<img class="asp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{templateData.animations.hotelsBar}}"/>',
              '<div class="asp-notifications-bar-text">{{templateData.strings.spSimilarHotelsNotificationMessage}}</div>',
            '</div>',
            '<div class="asp-notifications-bar-popular-hotels a-sp-notifications-hidden">',
              '<img class=asp-notifications-bar-image" src="{{templateData.images.hotelsBar}}"/>',
              '<img class="aasp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{templateData.animations.hotelsBar}}"/>',
              '<div class="asp-notifications-bar-text">{{templateData.strings.spCityHotelNotificationMessage}}<span class="asp-notifications-bar-city-text"></span></div>',
            '</div>',
            '<div class="asp-notifications-bar-coupons a-sp-notifications-hidden">',
              '<img class="asp-notifications-bar-image" src="{{templateData.images.couponsBar}}"/>',
              '<img class="asp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{templateData.animations.couponsBar}}"/>',
              '<div class="asp-notifications-bar-text">{{templateData.strings.spCouponsNotificationMessage}}</div>',
            '</div>',
            '<div class="asp-notifications-bar-offers-and-coupons a-sp-notifications-hidden">',
              '<img class="asp-notifications-bar-image" src="{{templateData.images.offersAndCouponsBar}}"/>',
              '<img class="asp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{templateData.animations.offersAndCouponsBar}}"/>',
              '<div class="asp-notifications-bar-text">{{templateData.strings.spOffersAndCouponsNotificationMessage}}</div>',
            '</div>',
            '<div class="asp-notifications-bar-deals a-sp-notifications-hidden">',
              '<img class="asp-notifications-bar-image" src="{{templateData.images.specialDealsBar}}">',
              '<img class="asp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{templateData.animations.specialDealsBar}}"/>',
              '<div class="asp-notifications-bar-text">{{templateData.strings.spBetterSpecialDealsNotificationBarMessage}}</div>',
            '</div>',
            '<div class="asp-notifications-bar-searching-deals a-sp-notifications-hidden">',
              '<img class="asp-notifications-bar-image" src="{{templateData.images.searching}}"/>',
              '<div class="asp-notifications-bar-content-two-rows">',
                '<div class="asp-notifications-bar-text">{{templateData.strings.spLoadingNotificationMessage}}</div>',
                '<div class="asp-notifications-bar-searching-subtext">{{templateData.strings.spLoadingNotificationDescriptionMessage}}</div>',
              '</div>',
            '</div>',
          '<div class="asp-notifications-bar-button">',
              '<span class="asp-notifications-bar-button-text">{{templateData.strings.spShowNotificationMessage}}</span>',
              '<span class="asp-notifications-bar-button-badge">',
                '<div class="asp-notifications-bar-button-badge-text"></div>',
              '</span>',
          '</div>',
          '</div>',
          '<div class="asp-notifications-bar-actions">',
            '<div class="asp-notifications-bar-gear-icon" id="settings-bar" style="background-image: url({{templateData.images.loadingNotificationGear}});"></div>',
            '<div class="asp-notifications-bar-close-icon" id="close-bar" style="background-image: url({{templateData.images.loadingNotificationClose}});"></div>',
          '</div>',
        '</div>',
    ],
    notificationRedirectBar:[
        '<div class="asp-notifications-redirect-bar-wrapper a-sp-notifications-hidden notranslate" id="asp-notifications-redirect-bar">',
        '<img class="asp-notifications-bar-logo" src="{{templateData.images.loadingNotificationLogo}}"/>',
        '<div class="asp-notification-bar-title">{{templateData.strings.spShowNotificationRedirectMessage}}</div>',
        '<div class="asp-notifications-bar-content">',
          '<div class="asp-notifications-bar-redirect-deal">',
            '{{#redirect.image}}',
              '<img class="asp-notifications-bar-redirect-deal-img" src="{{redirect.image}}"/>',
            '{{/redirect.image}}',
            '{{^redirect.image}}',
              '<div class="asp-blank-div"></div>',
            '{{/redirect.image}}',
            '<div class="asp-notifications-bar-redirect-deal-description">',
              '<div class="asp-notifications-bar-redirect-deal-title">{{redirect.label}}</div>',
              '<div class="asp-notifications-bar-redirect-deal-subtitle">{{redirect.availability}}</div>',
            '</div>',
            '<div class="asp-notification-bar-redirect-deal-info-wrapper">',
            '{{#redirect.infoText}}',
              '<img class="asp-notifications-bar-redirect-deal-info-img" src="{{templateData.images.info}}"/>',
              '<div class="asp-notification-bar-redirect-deal-info-box"><div class="asp-notifications-bar-redirect-deal-info-text">{{redirect.infoText}}</div></div>',
            '{{/redirect.infoText}}',
            '</div>',
          '</div>',
          '<div class="asp-notifications-bar-button" resurl="{{redirect.url}}">',
            '<span class="asp-notifications-bar-button-text">{{templateData.strings.spNotificationRedirectShowRedirectMessage}}</span>',
            '<img class="asp-notifications-bar-button-arrow" src="{{templateData.images.arrow}}"/>',
          '</div>',
        '</div>',
        '<div class="asp-notifications-bar-actions">',
          '<div class="asp-notifications-bar-gear-icon" id="settings-bar" style="background-image: url({{templateData.images.loadingNotificationGear}});"></div>',
          '<div class="asp-notifications-bar-close-icon" id="close-bar" style="background-image: url({{templateData.images.loadingNotificationClose}});"></div>',
        '</div>',
        '</div>',
    ],
    feedback: [
        '<div class="a-sp-feedback notranslate a-sp-feedback-hidden" id="a-sp-feedback-container">',
          {temp: "feedbackQuestionContainer"},
          {temp: "feedbackPositiveReactionContainer"},
          {temp: "feedbackNegativeReactionContainer"},
        '</div>'
    ],
    feedbackQuestionContainer: [
        '<div id="a-sp-feedback-action-question" class="a-sp-feedback-question">',
          '<img class="a-sp-feedback-question-logo" src="{{templateData.images.logoSP32x32}}"/>',
          '<p class="a-sp-feedback-question-text">{{{templateData.strings.safePriceEnjoyQuestion_Avast}}}{{{templateData.strings.safePriceEnjoyQuestion_AVG}}}</p>',
          '<div class="a-sp-feedback-question-buttons-container">',
              '<div class="a-sp-feedback-question-buttons-yes">{{{templateData.strings.sasAnswerYes}}}</div>',
              '<div class="a-sp-feedback-question-buttons-no">{{{templateData.strings.sasAnswerNo}}}</div>',
          '</div>',
          '<div class="a-sp-feedback-question-later">{{{templateData.strings.safePriceAskMeLater}}}</div>',
        '</div>'
    ],
    feedbackPositiveReactionContainer: [
        '<div id="a-sp-feedback-action-positive" class="a-sp-feedback-action a-sp-feedback-hidden">',
          '<div class="a-sp-feedback-action-header">',
              '<div></div>',
              '<img id="a-sp-feedback-action-close-positive" class="a-sp-feedback-action-close-img" src="{{templateData.images.closeIcon}}"/>',
          '</div>',
          '<div class="a-sp-feedback-action-img-container">',
              '<img class="a-sp-feedback-action-img" src="{{templateData.images.positiveFeedback}}"/>',
          '</div>',
          '<div class="a-sp-feedback-action-text-container">',
              '<span class="a-sp-feedback-action-text-content">{{{templateData.strings.sasGladYouLike}}}</span>',
          '</div>',
          '<div class="a-sp-feedback-action-description-container">',
            '<span class="a-sp-feedback-action-description-content">{{{templateData.strings.safePriceLeaveRating}}}</span>',
          '</div>',
          '<div class="a-sp-feedback-action-button-container">',
            '<span id="a-sp-feedback-action-button-positive" class="a-sp-feedback-action-button-content">{{{templateData.strings.sasRate}}}</span>',
          '</div>',
        '</div>'
    ],
    feedbackNegativeReactionContainer: [
        '<div id="a-sp-feedback-action-negative" class="a-sp-feedback-action a-sp-feedback-hidden">',
          '<div class="a-sp-feedback-action-header">',
              '<div></div>',
              '<img id="a-sp-feedback-action-close-negative" class="a-sp-feedback-action-close-img" src="{{templateData.images.closeIcon}}"/>',
          '</div>',
          '<div class="a-sp-feedback-action-img-container">',
              '<img class="a-sp-feedback-action-img" src="{{templateData.images.negativeFeedback}}"/>',
          '</div>',
          '<div class="a-sp-feedback-action-text-container">',
              '<span class="a-sp-feedback-action-text-content">{{{templateData.strings.sasSorry}}}</span>',
          '</div>',
          '<div class="a-sp-feedback-action-description-container">',
              '<span class="a-sp-feedback-action-description-content">{{{templateData.strings.sasWhatToDo}}}</span>',
          '</div>',
          '<div class="a-sp-feedback-action-button-container">',
              '<span id="a-sp-feedback-action-button-negative" class="a-sp-feedback-action-button-content">{{{templateData.strings.sasfeedback}}}</span>',
          '</div>',
        '</div>'
    ],
    socialSharing: [
        '<div class="a-sp-social notranslate" id="a-sp-social-container">',
          '<div class="a-sp-social-close-container">',
              '<img class="a-sp-social-close-img" src="{{{panelData.socialSharing.templateData.images.closeIcon12x12}}}">',
          '</div>',
          '<div class="a-sp-social-title-container">',
            '{{{panelData.socialSharing.templateData.strings.spSocialShare}}}',
          '</div>',
          '<div class="a-sp-social-buttons-container">',
            '<div class="a-sp-social-buttons-fb-container">',
                '<img class="a-sp-social-buttons-fb-img" src="{{{panelData.socialSharing.templateData.images.fbLogo5x11}}}">',
                '<img class="a-sp-social-buttons-fb-img" src="{{{panelData.socialSharing.templateData.images.fbLogo5x11}}}">',
                '<img class="a-sp-social-buttons-fb-img-action a-sp-social-hidden" src="{{{panelData.socialSharing.templateData.images.fbLogo5x11HoverAndActive}}}">',
                '<span class="a-sp-social-buttons-fb-text">{{{panelData.socialSharing.templateData.strings.spSocialShareFb}}}</span>',
            '</div>',
            '<div class="a-sp-social-buttons-tttr-container">',
              '<img class="a-sp-social-buttons-tttr-img" src="{{{panelData.socialSharing.templateData.images.tttrLogo5x11}}}">',
              '<img class="a-sp-social-buttons-tttr-img-action a-sp-social-hidden" src="{{{panelData.socialSharing.templateData.images.tttrLogo5x11HoverAndActive}}}">',
              '<span class="a-sp-social-buttons-tttr-text">{{{panelData.socialSharing.templateData.strings.spSocialSharetttr}}}</span>',
            '</div>',
          '</div>',
        '</div>'
    ]
    // --ende templates declarations --
  });
